name: GitHub FaaS — Random Excuse

on:
  workflow_dispatch:    
  schedule:
    - cron: '0 */6 * * *' 

jobs:
  run-function:
    runs-on: ubuntu-latest

    steps:
      - name: Клонування репозиторію
        uses: actions/checkout@v4

      - name: Встановлення Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Встановлення залежностей
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin

      - name: Запуск функції (FaaS)
        env:
          FIREBASE_KEY_JSON: ${{ secrets.FIREBASE_KEY_JSON }}
        run: python function.py
